version: 0.2

env:
  parameter-store:
    # NOT: AWS Systems Manager (SSM) Parameter Store'da daha önceden 
    # oluşturduğun şifre kasasının isimlerini buraya yazmalısın.
    DOCKER_USER: "/flask-projesi/dockerhub-username"
    DOCKER_PASS: "/flask-projesi/dockerhub-token"

phases:
  pre_build:
    commands:
      - echo "Docker Hub'a giris yapiliyor..."
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  build:
    commands:
      - echo "Docker imaji insa ediliyor..."
      # DİKKAT: seyhmusok yazan yeri kendi Docker Hub kullanıcı adınla değiştir!
      - docker build -t seyhmusok/benim-cloudformationtemplate-python-app:latest .
  post_build:
    commands:
      - echo "Imaj Docker Hub'a gonderiliyor..."
      - docker push seyhmusok/benim-cloudformationtemplate-python-app:latest
      - echo "Gorev basariyla tamamlandi Komutanım!"